<?php

namespace MyBlogBundle\Repository;

/**
 * ArticleEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
